export enum StudentsAction {
  SET_ACTIVE_STUDENTS = 'SET_ACTIVE_STUDENTS',
  SET_FOR_INTERVIEW_STUDENTS = 'SET_FOR_INTERVIEW_STUDENTS',
  SET_DATA_TYPE = 'SET_DATA_TYPE',
  SET_ACTUAL_SEARCH_PHRASE = 'SET_ACTUAL_SEARCH_PHRASE',
}